version: "3.6"

services:
 test:
  build: ./test/
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/metadata_cache/"
    - "./test/minetest.conf:/minetest.conf"
    - "world:/root/.minetest/worlds/world"
  ports:
    - "30000:30000/udp"

volumes:
  world: {}